services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80" # Expose port 80 ke host
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend_dev
      - backend_dev
      - frontend_staging
      - backend_staging
      - frontend_prod
      - backend_prod

  frontend_dev:
    build:
      context: ./frontend
      args:
        NODE_ENV: development
    container_name: frontend_dev
    ports:
      - "3001:80" # Dev environment
    environment:
      VITE_BACKEND_URL: http://backend_dev:5000
      VITE_ENV: development

  frontend_staging:
    build:
      context: ./frontend
      args:
        NODE_ENV: staging
    container_name: frontend_staging
    ports:
      - "3002:80" # Staging environment
    environment:
      VITE_BACKEND_URL: http://backend_staging:5000
      VITE_ENV: staging

  frontend_prod:
    build:
      context: ./frontend
      args:
        NODE_ENV: production
    container_name: frontend_prod
    ports:
      - "3003:80" # Production environment
    environment:
      VITE_BACKEND_URL: http://backend_prod:5000
      VITE_ENV: production

  backend_dev:
    build:
      context: ./backend
      args:
        NODE_ENV: development
        MONGODB_URI: mongodb://mongo:27017/note_db_dev
        REDIS_HOST: redis
        SESSION_SECRET: dev_secret
    container_name: backend_dev
    ports:
      - "5001:5000"
    depends_on:
      - mongo
      - redis

  backend_staging:
    build:
      context: ./backend
      args:
        NODE_ENV: staging
        MONGODB_URI: mongodb://mongo:27017/note_db_staging
        REDIS_HOST: redis
        SESSION_SECRET: staging_secret
    container_name: backend_staging
    ports:
      - "5002:5000"
    depends_on:
      - mongo
      - redis

  backend_prod:
    build:
      context: ./backend
      args:
        NODE_ENV: production
        MONGODB_URI: mongodb://mongo:27017/note_db_prod
        REDIS_HOST: redis
        SESSION_SECRET: prod_secret
    container_name: backend_prod
    ports:
      - "5003:5000"
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  mongo-data: